<table>
    <tr>
        <th>Subject</th>
        <th>Created</th>
        <th>Last activity</th>
        <th>Status</th>
    </tr>
    <tr>
        <td>DNS</td>
        <td>15/04/2021</td>
        <td>19/04/2021</td>
        <td>Closed</td>
    </tr>
    <tr>
        <td>DNS</td>
        <td>15/04/2021</td>
        <td>19/04/2021</td>
        <td>Closed</td>
    </tr>
</table>
